// Package imports:
import 'package:injectable/injectable.dart';

// Project imports:
import 'package:turna/application/ai/ai_course_explainer.dart';
import 'package:turna/application/ai/ai_course_service.dart';
import 'package:turna/application/ai/ai_course_spec.dart';
import 'package:turna/application/ai/ai_error_mapper.dart';
import 'package:turna/application/ai/ai_grounded_resource_provider.dart';
import 'package:turna/application/ai/ai_prompt_builder.dart';
import 'package:turna/application/ai/ai_recent_task_log.dart';
import 'package:turna/application/ai/ai_streaming_session_base.dart';
import 'package:turna/application/ai/engine/ai_cancel_token.dart';
import 'package:turna/application/ai/engine/ai_engine.dart';
import 'package:turna/application/ai/engine/ai_engine_config.dart';
import 'package:turna/application/ai/engine/ai_recent_tasks_provider.dart';
import 'package:turna/application/language_provider.dart';
import 'package:turna/application/language_registry.dart';
import 'package:turna/core/logger.dart';
import 'package:turna/di/injection.dart';
import 'package:turna/domain/course/lesson.dart';

/// State machine for the AI lesson helper.
enum AiLessonHelperState { idle, loading, ready, error, applying }

/// Provider that transforms a single lesson based on a natural-language
/// instruction. Mirrors tool-gui's `ai_lesson_helper_dialog.py`.
///
/// All LLM traffic routes through the shared [AiEngine]; a transform can be
/// cancelled mid-flight via [cancel]. Pure helpers
/// ([AiCourseService.parseCompletion]) are reused from a helper
/// [AiCourseService] instance.
@lazySingleton
class AiLessonHelperProvider extends AiRequestSessionBase {
  AiLessonHelperProvider({
    AiEngine? engine,
    AiGroundedResourceProvider? groundedProvider,
  })  : _engine = engine ?? getIt<AiEngine>(),
        _service = AiCourseService(),
        _groundedProvider = groundedProvider ?? AiGroundedResourceProvider();

  AiLessonHelperProvider.withEngine(
    this._engine, {
    AiGroundedResourceProvider? groundedProvider,
  })  : _service = AiCourseService(),
        _groundedProvider = groundedProvider ?? AiGroundedResourceProvider();

  final AiEngine _engine;
  final AiCourseService _service;
  final AiGroundedResourceProvider _groundedProvider;

  /// Target language for generated-course explanations: the learner's
  /// current language when DI is up (app runtime), the registry default in
  /// tests.
  static String _currentLanguageName() {
    if (getIt.isRegistered<LanguageProvider>()) {
      return getIt<LanguageProvider>().displayName;
    }
    return LanguageRegistry.instance.defaultLanguage.displayName;
  }

  AiLessonHelperState _state = AiLessonHelperState.idle;
  AiLessonHelperState get state => _state;

  String? _error;
  String? get error => _error;

  /// Original lesson passed in by the caller.
  Lesson? _originalLesson;
  Lesson? get originalLesson => _originalLesson;

  /// JSON representation of the transformed lesson. Kept as a map so callers
  /// can preview it before converting back to a [Lesson].
  Map<String, dynamic>? _resultJson;
  Map<String, dynamic>? get resultJson => _resultJson;

  /// User-facing explanation generated by the AI (optional).
  String? _explanation;
  String? get explanation => _explanation;

  void reset() {
    abandonStreamingSession();
    _state = AiLessonHelperState.idle;
    _error = null;
    _originalLesson = null;
    _resultJson = null;
    _explanation = null;
    notifySessionListeners();
  }

  /// Cancel the in-flight transform (if any) and return to idle, keeping the
  /// loaded lesson. A no-op when not loading.
  void cancel() {
    if (_state != AiLessonHelperState.loading) return;
    cancelStreamingSession();
    _state = AiLessonHelperState.idle;
    notifySessionListeners();
  }

  /// Set the lesson to be transformed without triggering a network call.
  void setLesson(Lesson lesson) {
    _originalLesson = lesson;
    _resultJson = null;
    _error = null;
    _state = AiLessonHelperState.idle;
    notifySessionListeners();
  }

  /// Transform the current lesson according to [instruction].
  Future<void> transform({
    required AiEngineConfig config,
    required String instruction,
  }) async {
    final lesson = _originalLesson;
    if (lesson == null) {
      _error = 'No lesson selected';
      _state = AiLessonHelperState.error;
      notifySessionListeners();
      return;
    }
    if (instruction.trim().isEmpty) return;

    final session = beginStreamingSession();
    _error = null;
    _state = AiLessonHelperState.loading;
    _resultJson = null;
    _explanation = null;
    notifySessionListeners();

    try {
      await _groundedProvider.load();
      final resourceIds = _groundedProvider.allResourceIds;
      final result = await _engine.requestJson(
        config: config,
        messages: <Map<String, dynamic>>[
          {
            'role': 'system',
            'content': 'You are a language-course authoring assistant. You output ONLY valid JSON, no prose, no markdown fences. '
                'You modify lesson content according to the teacher\'s instruction. '
                'Preserve all existing IDs. Only create new IDs for genuinely new content.',
          },
          {
            'role': 'user',
            'content': buildLessonTransformPrompt(
              lessonJson: lesson.toJson(),
              instruction: instruction.trim(),
              resourceIds: resourceIds,
            ),
          },
        ],
        temperature: 0.4,
        timeout: const Duration(seconds: 120),
        cancelToken: session.cancelToken,
      );
      if (!isCurrentSession(session)) return;
      final course = _service.parseCompletion(result.body);
      _resultJson = course.parsed;
      _state = AiLessonHelperState.ready;
      recordAiRecentTask(
        kind: AiTaskKind.lessonHelper,
        summary: course.parsed['id'] as String? ?? 'lesson',
      );
      try {
        final explanation = await explainGeneratedCourse(
          engine: _engine,
          config: config,
          spec: AiCourseSpec(
            language: _currentLanguageName(),
            topic: '',
            level: 'A1',
            unitCount: 1,
            lessonsPerUnit: 1,
          ),
          sectionJson: _wrapAsSection(course.parsed),
          cancelToken: session.cancelToken,
        );
        if (isCurrentSession(session)) _explanation = explanation;
      } catch (e) {
        logger.w('AiLessonHelperProvider explain failed: $e');
        if (isCurrentSession(session)) _explanation = null;
      }
    } on AiCancelled {
      if (!isCurrentSession(session)) return;
      _state = AiLessonHelperState.idle;
    } catch (e) {
      if (!isCurrentSession(session)) return;
      logger.w('AiLessonHelperProvider.transform failed: $e');
      _error = AiErrorMapper.map(e).message;
      _state = AiLessonHelperState.error;
    } finally {
      finishStreamingSession(session);
    }
    notifySessionListeners();
  }

  /// Wrap a single lesson JSON in a minimal section wrapper so the explain
  /// prompt can consume it.
  Map<String, dynamic> _wrapAsSection(Map<String, dynamic> lessonJson) {
    return <String, dynamic>{
      'id': 'ai-helper-section',
      'name': lessonJson['name'] ?? 'Modified lesson',
      'description': lessonJson['description'] ?? '',
      'units': [
        {
          'id': 'ai-helper-unit',
          'name': 'Unit',
          'lessons': [lessonJson],
        }
      ],
    };
  }
}
