// Flutter imports:
import 'package:flutter/foundation.dart';

// Package imports:
import 'package:http/http.dart' as http;

// Project imports:
import 'package:varnamala/application/ai/ai_api_config.dart';
import 'package:varnamala/application/ai/ai_course_service.dart';
import 'package:varnamala/application/ai/ai_course_spec.dart';
import 'package:varnamala/application/ai/ai_grounded_resource_provider.dart';
import 'package:varnamala/core/logger.dart';
import 'package:varnamala/domain/course/lesson.dart';

/// State machine for the AI lesson helper.
enum AiLessonHelperState { idle, loading, ready, error, applying }

/// Provider that transforms a single lesson based on a natural-language
/// instruction. Mirrors tool-gui's `ai_lesson_helper_dialog.py`.
class AiLessonHelperProvider extends ChangeNotifier {
  AiLessonHelperProvider({
    http.Client? client,
    AiGroundedResourceProvider? groundedProvider,
  })  : _service = AiCourseService(client: client),
        _groundedProvider = groundedProvider ?? AiGroundedResourceProvider();

  AiLessonHelperProvider.withService(
    this._service, {
    AiGroundedResourceProvider? groundedProvider,
  }) : _groundedProvider = groundedProvider ?? AiGroundedResourceProvider();

  final AiCourseService _service;
  final AiGroundedResourceProvider _groundedProvider;

  AiLessonHelperState _state = AiLessonHelperState.idle;
  AiLessonHelperState get state => _state;

  String? _error;
  String? get error => _error;

  /// Original lesson passed in by the caller.
  Lesson? _originalLesson;
  Lesson? get originalLesson => _originalLesson;

  /// JSON representation of the transformed lesson. Kept as a map so callers
  /// can preview it before converting back to a [Lesson].
  Map<String, dynamic>? _resultJson;
  Map<String, dynamic>? get resultJson => _resultJson;

  /// User-facing explanation generated by the AI (optional).
  String? _explanation;
  String? get explanation => _explanation;

  void reset() {
    _state = AiLessonHelperState.idle;
    _error = null;
    _originalLesson = null;
    _resultJson = null;
    _explanation = null;
    notifyListeners();
  }

  /// Set the lesson to be transformed without triggering a network call.
  void setLesson(Lesson lesson) {
    _originalLesson = lesson;
    _resultJson = null;
    _error = null;
    _state = AiLessonHelperState.idle;
    notifyListeners();
  }

  /// Transform the current lesson according to [instruction].
  Future<void> transform({
    required AiApiConfig config,
    required String instruction,
  }) async {
    final lesson = _originalLesson;
    if (lesson == null) {
      _error = 'No lesson selected';
      _state = AiLessonHelperState.error;
      notifyListeners();
      return;
    }
    if (instruction.trim().isEmpty) return;

    _error = null;
    _state = AiLessonHelperState.loading;
    _resultJson = null;
    _explanation = null;
    notifyListeners();

    try {
      await _groundedProvider.load();
      final resourceIds = _groundedProvider.allResourceIds;
      final result = await _service.requestLessonTransform(
        config: config,
        lessonJson: lesson.toJson(),
        instruction: instruction.trim(),
        resourceIds: resourceIds,
      );
      _resultJson = result.parsed;
      _state = AiLessonHelperState.ready;
      try {
        _explanation = await _service.explainCourse(
          config: config,
          spec: const AiCourseSpec(
            language: 'Turkish',
            topic: '',
            level: 'A1',
            unitCount: 1,
            lessonsPerUnit: 1,
          ),
          sectionJson: _wrapAsSection(result.parsed),
        );
      } catch (e) {
        logger.w('AiLessonHelperProvider explain failed: $e');
        _explanation = null;
      }
    } catch (e) {
      logger.w('AiLessonHelperProvider.transform failed: $e');
      _error = e.toString();
      _state = AiLessonHelperState.error;
    }
    notifyListeners();
  }

  /// Wrap a single lesson JSON in a minimal section wrapper so the existing
  /// [AiCourseService.explainCourse] can consume it.
  Map<String, dynamic> _wrapAsSection(Map<String, dynamic> lessonJson) {
    return <String, dynamic>{
      'id': 'ai-helper-section',
      'name': lessonJson['name'] ?? 'Modified lesson',
      'description': lessonJson['description'] ?? '',
      'units': [
        {
          'id': 'ai-helper-unit',
          'name': 'Unit',
          'lessons': [lessonJson],
        }
      ],
    };
  }
}
