// Flutter imports:
import 'package:flutter/foundation.dart';

// Package imports:
import 'package:injectable/injectable.dart';

// Project imports:
import 'package:varnamala/application/ai/ai_course_service.dart';
import 'package:varnamala/application/ai/ai_course_spec.dart';
import 'package:varnamala/application/ai/ai_grounded_resource_provider.dart';
import 'package:varnamala/application/ai/ai_prompt_builder.dart';
import 'package:varnamala/application/ai/engine/ai_cancel_token.dart';
import 'package:varnamala/application/ai/engine/ai_engine.dart';
import 'package:varnamala/application/ai/engine/ai_engine_config.dart';
import 'package:varnamala/application/ai/engine/ai_recent_tasks_provider.dart';
import 'package:varnamala/core/logger.dart';
import 'package:varnamala/di/injection.dart';
import 'package:varnamala/domain/course/lesson.dart';

/// State machine for the AI lesson helper.
enum AiLessonHelperState { idle, loading, ready, error, applying }

/// Provider that transforms a single lesson based on a natural-language
/// instruction. Mirrors tool-gui's `ai_lesson_helper_dialog.py`.
///
/// All LLM traffic routes through the shared [AiEngine]; a transform can be
/// cancelled mid-flight via [cancel]. Pure helpers
/// ([AiCourseService.parseCompletion]) are reused from a helper
/// [AiCourseService] instance.
@lazySingleton
class AiLessonHelperProvider extends ChangeNotifier {
  AiLessonHelperProvider({
    AiEngine? engine,
    AiGroundedResourceProvider? groundedProvider,
  })  : _engine = engine ?? getIt<AiEngine>(),
        _service = AiCourseService(),
        _groundedProvider = groundedProvider ?? AiGroundedResourceProvider();

  AiLessonHelperProvider.withEngine(
    this._engine, {
    AiGroundedResourceProvider? groundedProvider,
  })  : _service = AiCourseService(),
        _groundedProvider = groundedProvider ?? AiGroundedResourceProvider();

  final AiEngine _engine;
  final AiCourseService _service;
  final AiGroundedResourceProvider _groundedProvider;

  /// Active cancel token for the in-flight transform, if any.
  AiCancelToken? _cancelToken;

  AiLessonHelperState _state = AiLessonHelperState.idle;
  AiLessonHelperState get state => _state;

  String? _error;
  String? get error => _error;

  /// Original lesson passed in by the caller.
  Lesson? _originalLesson;
  Lesson? get originalLesson => _originalLesson;

  /// JSON representation of the transformed lesson. Kept as a map so callers
  /// can preview it before converting back to a [Lesson].
  Map<String, dynamic>? _resultJson;
  Map<String, dynamic>? get resultJson => _resultJson;

  /// User-facing explanation generated by the AI (optional).
  String? _explanation;
  String? get explanation => _explanation;

  void reset() {
    _cancelToken?.cancel();
    _cancelToken = null;
    _state = AiLessonHelperState.idle;
    _error = null;
    _originalLesson = null;
    _resultJson = null;
    _explanation = null;
    notifyListeners();
  }

  /// Cancel the in-flight transform (if any) and return to idle, keeping the
  /// loaded lesson. A no-op when not loading.
  void cancel() {
    if (_state != AiLessonHelperState.loading) return;
    _cancelToken?.cancel();
    _cancelToken = null;
    _state = AiLessonHelperState.idle;
    notifyListeners();
  }

  /// Set the lesson to be transformed without triggering a network call.
  void setLesson(Lesson lesson) {
    _originalLesson = lesson;
    _resultJson = null;
    _error = null;
    _state = AiLessonHelperState.idle;
    notifyListeners();
  }

  /// Transform the current lesson according to [instruction].
  Future<void> transform({
    required AiEngineConfig config,
    required String instruction,
  }) async {
    final lesson = _originalLesson;
    if (lesson == null) {
      _error = 'No lesson selected';
      _state = AiLessonHelperState.error;
      notifyListeners();
      return;
    }
    if (instruction.trim().isEmpty) return;

    _cancelToken?.cancel();
    final token = AiCancelToken();
    _cancelToken = token;
    _error = null;
    _state = AiLessonHelperState.loading;
    _resultJson = null;
    _explanation = null;
    notifyListeners();

    try {
      await _groundedProvider.load();
      final resourceIds = _groundedProvider.allResourceIds;
      final result = await _engine.requestJson(
        config: config,
        messages: <Map<String, dynamic>>[
          {
            'role': 'system',
            'content':
                'You are a language-course authoring assistant. You output ONLY valid JSON, no prose, no markdown fences. '
                'You modify lesson content according to the teacher\'s instruction. '
                'Preserve all existing IDs. Only create new IDs for genuinely new content.',
          },
          {
            'role': 'user',
            'content': buildLessonTransformPrompt(
              lessonJson: lesson.toJson(),
              instruction: instruction.trim(),
              resourceIds: resourceIds,
            ),
          },
        ],
        temperature: 0.4,
        timeout: const Duration(seconds: 120),
        cancelToken: token,
      );
      final course = _service.parseCompletion(result.body);
      _resultJson = course.parsed;
      _state = AiLessonHelperState.ready;
      _recordRecent();
      try {
        _explanation = await _explainCourse(
          config: config,
          spec: const AiCourseSpec(
            language: 'Turkish',
            topic: '',
            level: 'A1',
            unitCount: 1,
            lessonsPerUnit: 1,
          ),
          sectionJson: _wrapAsSection(course.parsed),
          token: token,
        );
      } catch (e) {
        logger.w('AiLessonHelperProvider explain failed: $e');
        _explanation = null;
      }
    } on AiCancelled {
      _state = AiLessonHelperState.idle;
    } catch (e) {
      logger.w('AiLessonHelperProvider.transform failed: $e');
      _error = e.toString();
      _state = AiLessonHelperState.error;
    } finally {
      if (identical(_cancelToken, token)) _cancelToken = null;
    }
    notifyListeners();
  }

  /// Plain-language explanation of the transformed lesson (mirrors the former
  /// `AiCourseService.explainCourse` prompt, now routed through the engine).
  Future<String> _explainCourse({
    required AiEngineConfig config,
    required AiCourseSpec spec,
    required Map<String, dynamic> sectionJson,
    required AiCancelToken token,
  }) async {
    final prompt =
        'You just generated the following course for a teacher with no '
        'technical background. Please explain in plain, easy-to-understand '
        '${spec.sourceLanguage}: the course\'s learning objectives, how units '
        'are divided, the key vocabulary / sentence patterns, and why it is '
        'designed this way. Do not output JSON or code.\n\n'
        'Course language: ${spec.language}\n'
        'Prompt language: ${spec.sourceLanguage}\n'
        'Level: ${spec.level}\n'
        'Course name: ${sectionJson['name'] ?? ''}\n'
        'Course description: ${sectionJson['description'] ?? ''}\n';
    final result = await _engine.chat(
      config: config,
      messages: <Map<String, dynamic>>[
        {
          'role': 'system',
          'content':
              'You are a language-course design assistant who explains course '
              'content in plain ${spec.sourceLanguage}.',
        },
        {'role': 'user', 'content': prompt},
      ],
      temperature: 0.6,
      timeout: const Duration(seconds: 120),
      cancelToken: token,
    );
    final content = result.content;
    return content.isEmpty ? '(AI returned no explanation)' : content;
  }

  /// Wrap a single lesson JSON in a minimal section wrapper so the explain
  /// prompt can consume it.
  Map<String, dynamic> _wrapAsSection(Map<String, dynamic> lessonJson) {
    return <String, dynamic>{
      'id': 'ai-helper-section',
      'name': lessonJson['name'] ?? 'Modified lesson',
      'description': lessonJson['description'] ?? '',
      'units': [
        {
          'id': 'ai-helper-unit',
          'name': 'Unit',
          'lessons': [lessonJson],
        }
      ],
    };
  }

  /// Append a lesson-helper transformation to the AI Hub's recent list.
  void _recordRecent() {
    try {
      final lessonId = _resultJson is Map<String, dynamic>
          ? _resultJson!['id'] as String?
          : null;
      getIt<AiRecentTasksProvider>().record(
            AiRecentTask(
              kind: AiTaskKind.lessonHelper,
              summary: lessonId ?? 'lesson',
              timestamp: DateTime.now(),
            ),
          );
    } catch (_) {
      // Advisory only.
    }
  }
}
