/// Level 1 vocabulary used by the match-words game.
/// Single-language build: the lookup map has been removed.
final allLevel1Words = <String, String>{
  "I": "Mimi",
  "You": "Wewe",
  "We": "Sisi",
  "Yes": "Ndiyo",
  "No": "Hapana",
  "Come": "Kuja",
  "Go": "Kwenda",
  "Name": "Jina",
  "Student": "Mwanafunzi",
  "Eat": "Kula",
  "Food": "Chakula",
  "Dog": "Mbwa",
  "Cat": "Paka",
  "Elephant": "Tembo",
  "Red": "Nyekundu",
  "Black": "Nyeusi",
  "Water": "Maji",
  "Tree": "Mti",
  "Happy": "Furaha",
  "Sad": "Huzuni",
  "Travel": "Safari",
  "Hello": "Jambo",
};
