"""Experience OS backend (Wave 0+): context bus, later intent/planner/skills.

Pure Python package — no Qt imports. See ``tool/gui/experienceai.md``.
"""
from __future__ import annotations

from src.backend.experience.actions import (
    ACTIONS,
    APP_BUILTIN_PREFIX,
    ActionSpec,
    DANGEROUS_ACTION_IDS,
    get_action,
    is_dangerous,
    is_dangerous_skill_allowed,
)
from src.backend.experience.context_bus import (
    ExperienceContext,
    NodeRef,
    build_experience_context,
    empty_lessons_among,
    local_suggestions,
    normalize_node,
)
from src.backend.experience.intent_router import (
    Intent,
    match_commands,
    route_intent,
)
from src.backend.experience.focus_ring import FocusEntry, FocusRole, FocusRing
from src.backend.experience.job_registry import (
    JOB_KIND_AI,
    JOB_KIND_LOCAL,
    JOB_KIND_VALIDATE,
    LEGACY_JOB_ID,
    JobRecord,
    JobRegistry,
)
from src.backend.experience.metrics import (
    ExperienceMetrics,
    course_attribution,
    export_snapshot,
    is_metrics_active,
    usage_today_from_summary,
)
from src.backend.experience.scope_format import (
    format_scope_target,
    has_yellow_quality_hints,
    infer_scope_node_key,
    yellow_quality_summary,
)
from src.backend.experience.patch import (
    BatchPatch,
    FieldPatch,
    ItemPatch,
    LessonPatch,
    PatchError,
    apply_field_patch,
    apply_item_patch,
    apply_lesson_patch,
    apply_resolved_batch,
    batch_patch,
    field_patch,
    item_patch_from_replace,
    lesson_patch_from_replace,
    revert_field_patch,
    revert_item_patch,
    revert_lesson_patch,
    revert_resolved_batch,
)
from src.backend.experience.policy import (
    ACTIVE,
    COPILOT,
    EXPERIENCE_MODES,
    IMMERSIVE,
    OBSERVER,
    PRESENCE_LEVEL_BY_MODE,
    PolicyDecision,
    can_dispatch,
    normalize_experience_mode,
    resolve_policy,
)
from src.backend.experience.soft_autopilot import (
    SoftFix,
    SoftFixBatch,
    apply_soft_fixes,
    evaluate_soft_fixes,
    summarize_soft_batch,
)
from src.backend.experience.workshop_draft import (
    build_workshop_draft,
    format_workshop_draft_line,
    normalize_workshop_draft,
)
from src.backend.experience.save_brief import (
    build_local_save_brief,
    build_local_save_brief_from_context,
)
from src.backend.experience.memory import (
    AuthorMemory,
    ExperienceMemory,
    IntentRecord,
    ProjectMemory,
    SessionMemory,
    assert_no_secrets,
    format_author_profile_line,
)
from src.backend.experience.planner import (
    GoalPlan,
    GoalStep,
    expand_goal_local,
    format_plan_summary,
    plan_from_context,
)
from src.backend.experience.sandbox import (
    CourseSandbox,
    MERGE_SELECT_CAP,
    MergeItem,
    MergePlan,
    adapter_lesson_fingerprint,
    filter_merge_plan,
    merge_item_key,
)
from src.backend.experience.publish_brief import (
    build_publish_brief,
    format_publish_brief_html,
)
from src.backend.experience.goal_generate import (
    build_stub_lesson,
    force_lesson_id,
    is_lesson_payload_mergeable,
)

__all__ = [
    "ACTIONS",
    "APP_BUILTIN_PREFIX",
    "ActionSpec",
    "ACTIVE",
    "COPILOT",
    "DANGEROUS_ACTION_IDS",
    "EXPERIENCE_MODES",
    "ExperienceContext",
    "ExperienceMetrics",
    "IMMERSIVE",
    "OBSERVER",
    "PRESENCE_LEVEL_BY_MODE",
    "PolicyDecision",
    "normalize_experience_mode",
    "course_attribution",
    "export_snapshot",
    "is_metrics_active",
    "usage_today_from_summary",
    "format_scope_target",
    "has_yellow_quality_hints",
    "infer_scope_node_key",
    "yellow_quality_summary",
    "BatchPatch",
    "FieldPatch",
    "FocusEntry",
    "FocusRole",
    "FocusRing",
    "Intent",
    "ItemPatch",
    "LessonPatch",
    "PatchError",
    "apply_field_patch",
    "apply_item_patch",
    "apply_lesson_patch",
    "apply_resolved_batch",
    "batch_patch",
    "field_patch",
    "item_patch_from_replace",
    "lesson_patch_from_replace",
    "revert_field_patch",
    "revert_item_patch",
    "revert_lesson_patch",
    "revert_resolved_batch",
    "JOB_KIND_AI",
    "JOB_KIND_LOCAL",
    "JOB_KIND_VALIDATE",
    "JobRecord",
    "JobRegistry",
    "LEGACY_JOB_ID",
    "NodeRef",
    "PatchError",
    "SoftFix",
    "SoftFixBatch",
    "apply_field_patch",
    "apply_item_patch",
    "apply_soft_fixes",
    "AuthorMemory",
    "CourseSandbox",
    "ExperienceMemory",
    "GoalPlan",
    "GoalStep",
    "IntentRecord",
    "MergeItem",
    "MergePlan",
    "ProjectMemory",
    "SessionMemory",
    "MERGE_SELECT_CAP",
    "adapter_lesson_fingerprint",
    "assert_no_secrets",
    "format_author_profile_line",
    "build_experience_context",
    "build_publish_brief",
    "build_stub_lesson",
    "expand_goal_local",
    "filter_merge_plan",
    "force_lesson_id",
    "format_plan_summary",
    "format_publish_brief_html",
    "is_lesson_payload_mergeable",
    "merge_item_key",
    "plan_from_context",
    "build_local_save_brief",
    "build_local_save_brief_from_context",
    "build_workshop_draft",
    "can_dispatch",
    "empty_lessons_among",
    "evaluate_soft_fixes",
    "format_workshop_draft_line",
    "summarize_soft_batch",
    "field_patch",
    "get_action",
    "is_dangerous",
    "is_dangerous_skill_allowed",
    "item_patch_from_replace",
    "local_suggestions",
    "match_commands",
    "normalize_node",
    "normalize_workshop_draft",
    "resolve_policy",
    "revert_field_patch",
    "revert_item_patch",
    "route_intent",
]
